[book]
title = "Rust By Practice"
description = "Learn Rust with Example, Exercise and real Practice, written with ❤️ by https://course.rs team"
authors = ["sunface, https://im.dev"]
language = "en"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.fold]
enable = true
level = 1

[output.html]
additional-css = ["theme/style1.css", "theme/quiz.css"]
additional-js = ["assets/custom3.js","assets/lang.js", "assets/diff.js", "assets/quiz.js"]
git-repository-url = "https://github.com/sunface/rust-by-practice"
edit-url-template = "https://github.com/sunface/rust-by-practice/edit/master/en/{path}"

[rust]
edition = "2021"